name: Build and Test

# When will this workflow run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y nasm
        sudo apt install -y mtools
        sudo apt install -y gcc-multilib
        sudo apt install -y grub-common
        sudo apt install -y xorriso
        sudo apt install -y qemu-system-x86
        sudo apt install -y bochs
        sudo apt install -y cppcheck
        
    - name: make
      run: make

    - uses: cpp-linter/cpp-linter-action@v2
      id: linter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        style: file

    - name: Check output of linting
      if: steps.linter.outputs.checks-failed > 0
      run: echo "Some files failed the linting checks!"
      # for actual deployment
      # run: exit 1

    - name: Run cppcheck
      run: cppcheck --error-exitcode=1 .

